//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 03:43:35 рм EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eu:faredge:drpp:di", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.faredge.dm.di;
