//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 03:43:35 рм EET 
//


package eu.faredge.dm.analytics.apd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.faredge.dm.analytics.apd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AdditionalInformation_QNAME = new QName("eu:faredge:analytics:apd", "AdditionalInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.faredge.dm.analytics.apd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link APD }
     * 
     */
    public APD createAPD() {
        return new APD();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eu:faredge:analytics:apd", name = "AdditionalInformation")
    public JAXBElement<Object> createAdditionalInformation(Object value) {
        return new JAXBElement<Object>(_AdditionalInformation_QNAME, Object.class, null, value);
    }

}
