//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:50:58 μμ EET 
//


package eu.faredge.dm.dsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import eu.faredge.dm.di.DI;
import eu.faredge.dm.dk.DK;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{eu:faredge:drpp:di}DI"/>
 *         &lt;element ref="{eu:faredge:drpp:dk}DK"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "di",
    "dk"
})
@XmlRootElement(name = "DSD")
public class DSD {

    @XmlElement(name = "DI", namespace = "eu:faredge:drpp:di", required = true)
    protected DI di;
    @XmlElement(name = "DK", namespace = "eu:faredge:drpp:dk", required = true)
    protected DK dk;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the di property.
     * 
     * @return
     *     possible object is
     *     {@link DI }
     *     
     */
    public DI getDI() {
        return di;
    }

    /**
     * Sets the value of the di property.
     * 
     * @param value
     *     allowed object is
     *     {@link DI }
     *     
     */
    public void setDI(DI value) {
        this.di = value;
    }

    /**
     * Gets the value of the dk property.
     * 
     * @return
     *     possible object is
     *     {@link DK }
     *     
     */
    public DK getDK() {
        return dk;
    }

    /**
     * Sets the value of the dk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DK }
     *     
     */
    public void setDK(DK value) {
        this.dk = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
