//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.27 at 04:45:46 μμ EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eu:faredge:drpp:dsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.faredge.dm.dsd;
