//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 08:50:10 μμ EET 
//


package eu.faredge.dm.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import eu.faredge.dm.di.DI;
import eu.faredge.dm.dk.DK;
import eu.faredge.dm.dsd.DSD;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{eu:faredge:drpp:dsd}DSD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:drpp:di}DI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:drpp:dk}DK" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dsd",
    "di",
    "dk"
})
@XmlRootElement(name = "DataDefinitions")
public class DataDefinitions {

    @XmlElement(name = "DSD", namespace = "eu:faredge:drpp:dsd")
    protected List<DSD> dsd;
    @XmlElement(name = "DI", namespace = "eu:faredge:drpp:di")
    protected List<DI> di;
    @XmlElement(name = "DK", namespace = "eu:faredge:drpp:dk")
    protected List<DK> dk;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the dsd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dsd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDSD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSD }
     * 
     * 
     */
    public List<DSD> getDSD() {
        if (dsd == null) {
            dsd = new ArrayList<DSD>();
        }
        return this.dsd;
    }

    /**
     * Gets the value of the di property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the di property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DI }
     * 
     * 
     */
    public List<DI> getDI() {
        if (di == null) {
            di = new ArrayList<DI>();
        }
        return this.di;
    }

    /**
     * Gets the value of the dk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DK }
     * 
     * 
     */
    public List<DK> getDK() {
        if (dk == null) {
            dk = new ArrayList<DK>();
        }
        return this.dk;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
