//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:50:58 μμ EET 
//


package eu.faredge.dm.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredgedm}Location" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredgedm}additionalInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:faredgedm}Device"/>
 *                   &lt;element ref="{eu:faredge:faredgedm}DataDefinitions"/>
 *                   &lt;element ref="{eu:faredge:faredgedm}Connections"/>
 *                   &lt;element ref="{eu:faredge:faredgedm}ProcessingDevices"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LiveData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:faredgedm}DeviceLD" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "location",
    "additionalInformation",
    "metaData",
    "liveData"
})
@XmlRootElement(name = "EdgeGateway")
public class EdgeGateway {

    protected String description;
    @XmlElement(name = "Location")
    protected Location location;
    protected List<Object> additionalInformation;
    @XmlElement(name = "MetaData", required = true)
    protected EdgeGateway.MetaData metaData;
    @XmlElement(name = "LiveData", required = true)
    protected EdgeGateway.LiveData liveData;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "namespace")
    protected String namespace;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * The Edge Gateway location
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<Object>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link EdgeGateway.MetaData }
     *     
     */
    public EdgeGateway.MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgeGateway.MetaData }
     *     
     */
    public void setMetaData(EdgeGateway.MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the liveData property.
     * 
     * @return
     *     possible object is
     *     {@link EdgeGateway.LiveData }
     *     
     */
    public EdgeGateway.LiveData getLiveData() {
        return liveData;
    }

    /**
     * Sets the value of the liveData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgeGateway.LiveData }
     *     
     */
    public void setLiveData(EdgeGateway.LiveData value) {
        this.liveData = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:faredgedm}DeviceLD" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deviceLD"
    })
    public static class LiveData {

        @XmlElement(name = "DeviceLD")
        protected List<DeviceLD> deviceLD;

        /**
         * Gets the value of the deviceLD property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deviceLD property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeviceLD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeviceLD }
         * 
         * 
         */
        public List<DeviceLD> getDeviceLD() {
            if (deviceLD == null) {
                deviceLD = new ArrayList<DeviceLD>();
            }
            return this.deviceLD;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:faredgedm}Device"/>
     *         &lt;element ref="{eu:faredge:faredgedm}DataDefinitions"/>
     *         &lt;element ref="{eu:faredge:faredgedm}Connections"/>
     *         &lt;element ref="{eu:faredge:faredgedm}ProcessingDevices"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "device",
        "dataDefinitions",
        "connections",
        "processingDevices"
    })
    public static class MetaData {

        @XmlElement(name = "Device", required = true)
        protected Device device;
        @XmlElement(name = "DataDefinitions", required = true)
        protected DataDefinitions dataDefinitions;
        @XmlElement(name = "Connections", required = true)
        protected Connections connections;
        @XmlElement(name = "ProcessingDevices", required = true)
        protected ProcessingDevices processingDevices;

        /**
         * Gets the value of the device property.
         * 
         * @return
         *     possible object is
         *     {@link Device }
         *     
         */
        public Device getDevice() {
            return device;
        }

        /**
         * Sets the value of the device property.
         * 
         * @param value
         *     allowed object is
         *     {@link Device }
         *     
         */
        public void setDevice(Device value) {
            this.device = value;
        }

        /**
         * Gets the value of the dataDefinitions property.
         * 
         * @return
         *     possible object is
         *     {@link DataDefinitions }
         *     
         */
        public DataDefinitions getDataDefinitions() {
            return dataDefinitions;
        }

        /**
         * Sets the value of the dataDefinitions property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataDefinitions }
         *     
         */
        public void setDataDefinitions(DataDefinitions value) {
            this.dataDefinitions = value;
        }

        /**
         * Gets the value of the connections property.
         * 
         * @return
         *     possible object is
         *     {@link Connections }
         *     
         */
        public Connections getConnections() {
            return connections;
        }

        /**
         * Sets the value of the connections property.
         * 
         * @param value
         *     allowed object is
         *     {@link Connections }
         *     
         */
        public void setConnections(Connections value) {
            this.connections = value;
        }

        /**
         * Gets the value of the processingDevices property.
         * 
         * @return
         *     possible object is
         *     {@link ProcessingDevices }
         *     
         */
        public ProcessingDevices getProcessingDevices() {
            return processingDevices;
        }

        /**
         * Sets the value of the processingDevices property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProcessingDevices }
         *     
         */
        public void setProcessingDevices(ProcessingDevices value) {
            this.processingDevices = value;
        }

    }

}
