//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.22 at 05:37:35 μμ EET 
//


package eu.faredge.dm.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import eu.faredge.dm.analytics.am.AM;
import eu.faredge.dm.analytics.ap.APM;
import eu.faredge.dm.analytics.apd.APD;
import eu.faredge.dm.dcd.DCD;
import eu.faredge.dm.di.DI;
import eu.faredge.dm.dk.DK;
import eu.faredge.dm.dsd.DSD;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredgedm}additionalInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DataDefinitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:drpp:dsd}DSD" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:drpp:di}DI" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:drpp:dk}DK" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:ea:apd}APD" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataManipulation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:drpp:dcd}DCD" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:ea:processor}APM" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:ea:orchestrator}AM" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{eu:faredge:faredgedm}EdgeGateway" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredgedm}LiveDataSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "additionalInformation",
    "dataDefinitions",
    "dataManipulation",
    "edgeGateway",
    "liveDataSet"
})
@XmlRootElement(name = "FarEdgeDM")
public class FarEdgeDM {

    protected String description;
    protected List<Object> additionalInformation;
    @XmlElement(name = "DataDefinitions", required = true)
    protected FarEdgeDM.DataDefinitions dataDefinitions;
    @XmlElement(name = "DataManipulation", required = true)
    protected FarEdgeDM.DataManipulation dataManipulation;
    @XmlElement(name = "EdgeGateway")
    protected List<EdgeGateway> edgeGateway;
    @XmlElement(name = "LiveDataSet")
    protected List<LiveDataSet> liveDataSet;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "namespace")
    protected String namespace;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<Object>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the dataDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link FarEdgeDM.DataDefinitions }
     *     
     */
    public FarEdgeDM.DataDefinitions getDataDefinitions() {
        return dataDefinitions;
    }

    /**
     * Sets the value of the dataDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEdgeDM.DataDefinitions }
     *     
     */
    public void setDataDefinitions(FarEdgeDM.DataDefinitions value) {
        this.dataDefinitions = value;
    }

    /**
     * Gets the value of the dataManipulation property.
     * 
     * @return
     *     possible object is
     *     {@link FarEdgeDM.DataManipulation }
     *     
     */
    public FarEdgeDM.DataManipulation getDataManipulation() {
        return dataManipulation;
    }

    /**
     * Sets the value of the dataManipulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEdgeDM.DataManipulation }
     *     
     */
    public void setDataManipulation(FarEdgeDM.DataManipulation value) {
        this.dataManipulation = value;
    }

    /**
     * Gets the value of the edgeGateway property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edgeGateway property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdgeGateway().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgeGateway }
     * 
     * 
     */
    public List<EdgeGateway> getEdgeGateway() {
        if (edgeGateway == null) {
            edgeGateway = new ArrayList<EdgeGateway>();
        }
        return this.edgeGateway;
    }

    /**
     * Gets the value of the liveDataSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the liveDataSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiveDataSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LiveDataSet }
     * 
     * 
     */
    public List<LiveDataSet> getLiveDataSet() {
        if (liveDataSet == null) {
            liveDataSet = new ArrayList<LiveDataSet>();
        }
        return this.liveDataSet;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:drpp:dsd}DSD" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:drpp:di}DI" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:drpp:dk}DK" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:ea:apd}APD" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dsd",
        "di",
        "dk",
        "apd"
    })
    public static class DataDefinitions {

        @XmlElement(name = "DSD", namespace = "eu:faredge:drpp:dsd")
        protected List<DSD> dsd;
        @XmlElement(name = "DI", namespace = "eu:faredge:drpp:di")
        protected List<DI> di;
        @XmlElement(name = "DK", namespace = "eu:faredge:drpp:dk")
        protected List<DK> dk;
        @XmlElement(name = "APD", namespace = "eu:faredge:ea:apd")
        protected List<APD> apd;

        /**
         * Gets the value of the dsd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dsd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDSD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DSD }
         * 
         * 
         */
        public List<DSD> getDSD() {
            if (dsd == null) {
                dsd = new ArrayList<DSD>();
            }
            return this.dsd;
        }

        /**
         * Gets the value of the di property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the di property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDI().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DI }
         * 
         * 
         */
        public List<DI> getDI() {
            if (di == null) {
                di = new ArrayList<DI>();
            }
            return this.di;
        }

        /**
         * Gets the value of the dk property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dk property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DK }
         * 
         * 
         */
        public List<DK> getDK() {
            if (dk == null) {
                dk = new ArrayList<DK>();
            }
            return this.dk;
        }

        /**
         * Gets the value of the apd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAPD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link APD }
         * 
         * 
         */
        public List<APD> getAPD() {
            if (apd == null) {
                apd = new ArrayList<APD>();
            }
            return this.apd;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:drpp:dcd}DCD" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:ea:processor}APM" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:ea:orchestrator}AM" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dcd",
        "apm",
        "am"
    })
    public static class DataManipulation {

        @XmlElement(name = "DCD", namespace = "eu:faredge:drpp:dcd")
        protected List<DCD> dcd;
        @XmlElement(name = "APM", namespace = "eu:faredge:ea:processor")
        protected List<APM> apm;
        @XmlElement(name = "AM", namespace = "eu:faredge:ea:orchestrator")
        protected List<AM> am;

        /**
         * Gets the value of the dcd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dcd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDCD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DCD }
         * 
         * 
         */
        public List<DCD> getDCD() {
            if (dcd == null) {
                dcd = new ArrayList<DCD>();
            }
            return this.dcd;
        }

        /**
         * Gets the value of the apm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAPM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link APM }
         * 
         * 
         */
        public List<APM> getAPM() {
            if (apm == null) {
                apm = new ArrayList<APM>();
            }
            return this.apm;
        }

        /**
         * Gets the value of the am property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the am property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AM }
         * 
         * 
         */
        public List<AM> getAM() {
            if (am == null) {
                am = new ArrayList<AM>();
            }
            return this.am;
        }

    }

}
