//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.27 at 04:45:46 μμ EEST 
//


package eu.faredge.dm.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import eu.faredge.dm.analytics.am.AM;
import eu.faredge.dm.analytics.apd.APD;
import eu.faredge.dm.analytics.apm.APM;
import eu.faredge.dm.dcd.DCD;
import eu.faredge.dm.di.DI;
import eu.faredge.dm.dk.DK;
import eu.faredge.dm.dsd.DSD;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredge:dm}AdditionalInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FDEM">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SDRMs" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SDRM" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DataSourceManifestReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                       &lt;element name="SimulationLogicalEntityAttributeReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataDefinitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:drpp:dsd}DSD" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:drpp:di}DI" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:drpp:dk}DK" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:analytics:apd}APD" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataManipulation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{eu:faredge:drpp:dcd}DCD" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:analytics:apm}APM" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{eu:faredge:analytics:orchestrator}AM" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{eu:faredge:faredge:dm}EdgeGateway" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{eu:faredge:faredge:dm}LiveDataSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespace",
    "description",
    "additionalInformation",
    "fdem",
    "dataDefinitions",
    "dataManipulation",
    "edgeGateway",
    "liveDataSet"
})
@XmlRootElement(name = "FarEdgeDM")
public class FarEdgeDM {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String namespace;
    protected String description;
    @XmlElement(name = "AdditionalInformation")
    protected List<Object> additionalInformation;
    @XmlElement(name = "FDEM", required = true)
    protected FarEdgeDM.FDEM fdem;
    @XmlElement(name = "DataDefinitions", required = true)
    protected FarEdgeDM.DataDefinitions dataDefinitions;
    @XmlElement(name = "DataManipulation", required = true)
    protected FarEdgeDM.DataManipulation dataManipulation;
    @XmlElement(name = "EdgeGateway")
    protected List<EdgeGateway> edgeGateway;
    @XmlElement(name = "LiveDataSet")
    protected List<LiveDataSet> liveDataSet;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<Object>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the fdem property.
     * 
     * @return
     *     possible object is
     *     {@link FarEdgeDM.FDEM }
     *     
     */
    public FarEdgeDM.FDEM getFDEM() {
        return fdem;
    }

    /**
     * Sets the value of the fdem property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEdgeDM.FDEM }
     *     
     */
    public void setFDEM(FarEdgeDM.FDEM value) {
        this.fdem = value;
    }

    /**
     * Gets the value of the dataDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link FarEdgeDM.DataDefinitions }
     *     
     */
    public FarEdgeDM.DataDefinitions getDataDefinitions() {
        return dataDefinitions;
    }

    /**
     * Sets the value of the dataDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEdgeDM.DataDefinitions }
     *     
     */
    public void setDataDefinitions(FarEdgeDM.DataDefinitions value) {
        this.dataDefinitions = value;
    }

    /**
     * Gets the value of the dataManipulation property.
     * 
     * @return
     *     possible object is
     *     {@link FarEdgeDM.DataManipulation }
     *     
     */
    public FarEdgeDM.DataManipulation getDataManipulation() {
        return dataManipulation;
    }

    /**
     * Sets the value of the dataManipulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEdgeDM.DataManipulation }
     *     
     */
    public void setDataManipulation(FarEdgeDM.DataManipulation value) {
        this.dataManipulation = value;
    }

    /**
     * Gets the value of the edgeGateway property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edgeGateway property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdgeGateway().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgeGateway }
     * 
     * 
     */
    public List<EdgeGateway> getEdgeGateway() {
        if (edgeGateway == null) {
            edgeGateway = new ArrayList<EdgeGateway>();
        }
        return this.edgeGateway;
    }

    /**
     * Gets the value of the liveDataSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the liveDataSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiveDataSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LiveDataSet }
     * 
     * 
     */
    public List<LiveDataSet> getLiveDataSet() {
        if (liveDataSet == null) {
            liveDataSet = new ArrayList<LiveDataSet>();
        }
        return this.liveDataSet;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:drpp:dsd}DSD" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:drpp:di}DI" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:drpp:dk}DK" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:analytics:apd}APD" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dsd",
        "di",
        "dk",
        "apd"
    })
    public static class DataDefinitions {

        @XmlElement(name = "DSD", namespace = "eu:faredge:drpp:dsd")
        protected List<DSD> dsd;
        @XmlElement(name = "DI", namespace = "eu:faredge:drpp:di")
        protected List<DI> di;
        @XmlElement(name = "DK", namespace = "eu:faredge:drpp:dk")
        protected List<DK> dk;
        @XmlElement(name = "APD", namespace = "eu:faredge:analytics:apd")
        protected List<APD> apd;

        /**
         * Gets the value of the dsd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dsd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDSD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DSD }
         * 
         * 
         */
        public List<DSD> getDSD() {
            if (dsd == null) {
                dsd = new ArrayList<DSD>();
            }
            return this.dsd;
        }

        /**
         * Gets the value of the di property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the di property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDI().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DI }
         * 
         * 
         */
        public List<DI> getDI() {
            if (di == null) {
                di = new ArrayList<DI>();
            }
            return this.di;
        }

        /**
         * Gets the value of the dk property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dk property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DK }
         * 
         * 
         */
        public List<DK> getDK() {
            if (dk == null) {
                dk = new ArrayList<DK>();
            }
            return this.dk;
        }

        /**
         * Gets the value of the apd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAPD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link APD }
         * 
         * 
         */
        public List<APD> getAPD() {
            if (apd == null) {
                apd = new ArrayList<APD>();
            }
            return this.apd;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{eu:faredge:drpp:dcd}DCD" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:analytics:apm}APM" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{eu:faredge:analytics:orchestrator}AM" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dcd",
        "apm",
        "am"
    })
    public static class DataManipulation {

        @XmlElement(name = "DCD", namespace = "eu:faredge:drpp:dcd")
        protected List<DCD> dcd;
        @XmlElement(name = "APM", namespace = "eu:faredge:analytics:apm")
        protected List<APM> apm;
        @XmlElement(name = "AM", namespace = "eu:faredge:analytics:orchestrator")
        protected List<AM> am;

        /**
         * Gets the value of the dcd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dcd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDCD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DCD }
         * 
         * 
         */
        public List<DCD> getDCD() {
            if (dcd == null) {
                dcd = new ArrayList<DCD>();
            }
            return this.dcd;
        }

        /**
         * Gets the value of the apm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAPM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link APM }
         * 
         * 
         */
        public List<APM> getAPM() {
            if (apm == null) {
                apm = new ArrayList<APM>();
            }
            return this.apm;
        }

        /**
         * Gets the value of the am property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the am property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AM }
         * 
         * 
         */
        public List<AM> getAM() {
            if (am == null) {
                am = new ArrayList<AM>();
            }
            return this.am;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SDRMs" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SDRM" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DataSourceManifestReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                             &lt;element name="SimulationLogicalEntityAttributeReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sdrMs"
    })
    public static class FDEM {

        @XmlElement(name = "SDRMs")
        protected FarEdgeDM.FDEM.SDRMs sdrMs;

        /**
         * Gets the value of the sdrMs property.
         * 
         * @return
         *     possible object is
         *     {@link FarEdgeDM.FDEM.SDRMs }
         *     
         */
        public FarEdgeDM.FDEM.SDRMs getSDRMs() {
            return sdrMs;
        }

        /**
         * Sets the value of the sdrMs property.
         * 
         * @param value
         *     allowed object is
         *     {@link FarEdgeDM.FDEM.SDRMs }
         *     
         */
        public void setSDRMs(FarEdgeDM.FDEM.SDRMs value) {
            this.sdrMs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SDRM" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DataSourceManifestReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                   &lt;element name="SimulationLogicalEntityAttributeReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sdrm"
        })
        public static class SDRMs {

            @XmlElement(name = "SDRM")
            protected List<FarEdgeDM.FDEM.SDRMs.SDRM> sdrm;

            /**
             * Gets the value of the sdrm property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sdrm property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSDRM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FarEdgeDM.FDEM.SDRMs.SDRM }
             * 
             * 
             */
            public List<FarEdgeDM.FDEM.SDRMs.SDRM> getSDRM() {
                if (sdrm == null) {
                    sdrm = new ArrayList<FarEdgeDM.FDEM.SDRMs.SDRM>();
                }
                return this.sdrm;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DataSourceManifestReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *         &lt;element name="SimulationLogicalEntityAttributeReferenceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dataSourceManifestReferenceID",
                "simulationLogicalEntityAttributeReferenceID"
            })
            public static class SDRM {

                @XmlElement(name = "DataSourceManifestReferenceID", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String dataSourceManifestReferenceID;
                @XmlElement(name = "SimulationLogicalEntityAttributeReferenceID", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String simulationLogicalEntityAttributeReferenceID;
                @XmlAttribute(name = "id")
                @XmlSchemaType(name = "anyURI")
                protected String id;

                /**
                 * Gets the value of the dataSourceManifestReferenceID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDataSourceManifestReferenceID() {
                    return dataSourceManifestReferenceID;
                }

                /**
                 * Sets the value of the dataSourceManifestReferenceID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDataSourceManifestReferenceID(String value) {
                    this.dataSourceManifestReferenceID = value;
                }

                /**
                 * Gets the value of the simulationLogicalEntityAttributeReferenceID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSimulationLogicalEntityAttributeReferenceID() {
                    return simulationLogicalEntityAttributeReferenceID;
                }

                /**
                 * Sets the value of the simulationLogicalEntityAttributeReferenceID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSimulationLogicalEntityAttributeReferenceID(String value) {
                    this.simulationLogicalEntityAttributeReferenceID = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }

    }

}
