//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.27 at 04:45:46 μμ EEST 
//


package eu.faredge.dm.core;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.faredge.dm.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AdditionalInformation_QNAME = new QName("eu:faredge:faredge:dm", "AdditionalInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.faredge.dm.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link FarEdgeDM.FDEM.SDRMs }
     * 
     */
    public FarEdgeDM.FDEM.SDRMs createFarEdgeDMFDEMSDRMs() {
        return new FarEdgeDM.FDEM.SDRMs();
    }

    /**
     * Create an instance of {@link LiveDataSet }
     * 
     */
    public LiveDataSet createLiveDataSet() {
        return new LiveDataSet();
    }

    /**
     * Create an instance of {@link Location.GeoLocation }
     * 
     */
    public Location.GeoLocation createLocationGeoLocation() {
        return new Location.GeoLocation();
    }

    /**
     * Create an instance of {@link FarEdgeDM.FDEM.SDRMs.SDRM }
     * 
     */
    public FarEdgeDM.FDEM.SDRMs.SDRM createFarEdgeDMFDEMSDRMsSDRM() {
        return new FarEdgeDM.FDEM.SDRMs.SDRM();
    }

    /**
     * Create an instance of {@link FarEdgeDM }
     * 
     */
    public FarEdgeDM createFarEdgeDM() {
        return new FarEdgeDM();
    }

    /**
     * Create an instance of {@link FarEdgeDM.DataDefinitions }
     * 
     */
    public FarEdgeDM.DataDefinitions createFarEdgeDMDataDefinitions() {
        return new FarEdgeDM.DataDefinitions();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link EdgeGateway.DataManifests }
     * 
     */
    public EdgeGateway.DataManifests createEdgeGatewayDataManifests() {
        return new EdgeGateway.DataManifests();
    }

    /**
     * Create an instance of {@link FarEdgeDM.FDEM }
     * 
     */
    public FarEdgeDM.FDEM createFarEdgeDMFDEM() {
        return new FarEdgeDM.FDEM();
    }

    /**
     * Create an instance of {@link EdgeGateway.DataManipulation }
     * 
     */
    public EdgeGateway.DataManipulation createEdgeGatewayDataManipulation() {
        return new EdgeGateway.DataManipulation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link ProcessingDevices }
     * 
     */
    public ProcessingDevices createProcessingDevices() {
        return new ProcessingDevices();
    }

    /**
     * Create an instance of {@link FarEdgeDM.DataManipulation }
     * 
     */
    public FarEdgeDM.DataManipulation createFarEdgeDMDataManipulation() {
        return new FarEdgeDM.DataManipulation();
    }

    /**
     * Create an instance of {@link EdgeGateway }
     * 
     */
    public EdgeGateway createEdgeGateway() {
        return new EdgeGateway();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eu:faredge:faredge:dm", name = "AdditionalInformation")
    public JAXBElement<Object> createAdditionalInformation(Object value) {
        return new JAXBElement<Object>(_AdditionalInformation_QNAME, Object.class, null, value);
    }

}
